### ISSUE TITLE
fix fee_quantity adding to previous not overwrite

### ISSUE THREAD

**Issue by vantessel** [vyper-protocol/vyper-core#72]

**Comment by vantessel** [comment]
here it should be added at the vyper core level and not at the redeem logic level? @thegreat-vanderlinde

**Comment by thegreat-vanderlinde** [comment]
I think the problem we noticed was that here:
https://github.com/vyper-protocol/vyper-core/blob/bf31d7bc2dcfa1b6a5978047698efade003b74cd/programs/vyper-core/src/instructions/refresh_tranche_fair_value.rs#L122-L126

we overwrite the fee quantity every time, instead the from the payoff plugin pov that quantity was mentioned to be added to the previous
